legitbiz/SealsOfFate

Assets/Prefabs/PlayerSeal.prefab
Assets/Scripts/AI.meta
Assets/Scripts/AI/States.meta
Assets/Scripts/AI/States/StateAsleep.cs
Assets/Scripts/AI/States/StateAsleep.cs.meta
Assets/Scripts/Enemy.cs
Assets/Scripts/Enemy.cs.meta
Assets/Scripts/State.cs
Assets/Scripts/State.cs.meta
Assets/Scripts/StateMachine.cs
Assets/Scripts/StateMachine.cs.meta

* Adds a basic state machine framework and an empty state StateAsleep
* Modifies PlayerSeal to contain a rigidbody and 2d box collider
* Adds a placeholder enemy script
* No baby seals were clubbed in the making of this patch

Adds a basic state machine. Modifies some prefabs and adds folders.

---

Assets/Scripts/MovingObject.cs
Assets/Scripts/Player.cs

-[] Prevents new movement from being processed until current movement has been completed

The Seal has had his caffeine toned down

---

Assets/Scripts/GameManager.cs
Assets/Scripts/LevelManager.cs
Assets/Scripts/MovingObject.cs
Assets/Scripts/Player.cs

* Gives penguins a stern talking to by HR so that they no longer attempt
to move into the same square as the player and hug them to death.
* Refactors isMoving in MovingObject and Player and pushes it to
GameManager instead.
* Makes isMoving global for all moving entities and true whenever
anything is moving. This prevents race conditions.
* Refactors entitiesToMove into a list instead of an array.
* Allows Penguins to have as many friends as the board space allows
without kludging in a specific amount of memory before-hand.

Refactors how enemies are updated.

---

README.md

Issues:
* Text is a little barebones at the moment.
* Planned features section is blank
* Copyright only lists A Legitimate Buisness and not names, this may or
may not want to be changed to actual names.

#46 Creates an actual readme for the project.

---

Assets/Scripts/Enemy.cs
Assets/Scripts/MovingObject.cs

* Enriches Penguin lives through the magic of dance
* Adds a function in MovingObject to raycast from current position
without attempting movement.
* Adds movement randomization when enemies are directly diagonal to the
player when seeking so that they don't always travel in the vertical
direction.
* Adds very basic obstacle avoidance by causing penguins to move in a
totally random direction when they would otherwise collide with an
obstacle or fellow penguin.

Implements basic placeholder obstacle avoidance for enemies

---

Assets/Scripts/LevelManager.cs
Assets/Scripts/MovingObject.cs
Assets/Scripts/Player.cs
Assets/Scripts/State.cs
Assets/Scripts/StateMachine.cs

Provides better comments and re-formats code to be more idiomatic C#.
WIP on #38

Formatting and commenting

---

Assets/Scripts/Entity/MovingObject.cs

Literally no idea how these ended up getting merged. I have failed us all.
This should finish what #49 started.

Removing merge conflicts

---

Assets/Prefabs/GameManager.prefab

Changes case of Columns and Rows in GameManager.prefab

---

Assets/Prefabs/Enemy.prefab
Assets/Prefabs/PlayerSeal.prefab
Assets/Scripts/Entity/MovingObject.cs

Tactical coffee has been deployed to speed up movement overall. Movement now takes 0.075 seconds rather than 0.100 seconds.

Tweaks the move speed of the seal and enemy prefabs

---

SealsOfFate.sln.DotSettings

Switches braces from BSD style to K&R style.

Switching up brace style

---

Assets/Scripts/Item/Collectable.cs
Assets/Scripts/Item/Consumable.cs
Assets/Scripts/Item/Consumables/Food.cs

This is part of the clean up effort from #38

Cleans up comments on collectable, consumable, and food

---

Assets/Scripts/Entity/Enemy.cs
Assets/Scripts/Entity/MovingObject.cs
Assets/Scripts/Entity/Player.cs

* Adds a constraint to AttemptMove to only work on components
* Adds a debug log message when an attack is made
* Refactors Player.cs to use the style settings submitted by @peschkaj 
* No seals were harmed in the making of this update, but they are getting nervous

implements placeholder combat and runs code style on Player.cs

---

Assets/Scripts/Entity/Player.cs
SealsOfFate.sln.DotSettings

Currently not connected to their associated combat structures.

Stats added to the player class. 

---

Assets/Editor/AttackInfoDrawer.cs
Assets/Scripts/Entity/Enemy.cs
Assets/Scripts/Entity/Player.cs
Assets/Scripts/GameManager.cs

- When an enemy's HP is depleted, it is removed from the board.
- When the player's HP is depleted, it is removed from the board and an Exception is thrown.
This should finish up #56 (Combat). Outstanding issues remain, but they're not specific to combat.

Finishes combat implementation

---

Assets/Scripts/AI/SearchAStar.cs
Assets/Scripts/Entity/Enemy.cs
Assets/Scripts/Utility/BucketQueue.cs

* Fixes #80
* Fixes #81
* Fixes a bug in BucketQueue where the iterator was not iterating
through all buckets
* Adds warning log messages in SearchAStar for unusual or undesirable
circumstances
* Refactors some vector.equals comparisons to == as per Unity doc
reccomendation.

Fixes several pathfinding bugs and adds logging

---

Assets/Scripts/Entity/Enemy.cs
Assets/Scripts/GameManager.cs
Assets/Scripts/Utility/StateMachine.cs

- Resharper run through GameManager.cs
- Logic clean up inside GameManager.Update to reduce nesting
- Adds comments to Enemy.cs
- Cleans up variable names in Enemy
WIP on #38 
Fixes #79 
Replaces #90

Formats GameManager.cs and Enemy.cs

---

Assets/Scripts/Entity/Enemy.cs
Assets/Scripts/GameManager.cs

- Abstracts state machine checks to methods on Enemy
- Returns @Zonr0's fixes for #79

Better sleep state management

---

Assets/Scripts/Utility/BucketQueue.cs

In preparation for turn system refactor
* Adds an indexer for the BucketQueue
* Modifies Remove to return a bool. Returns true if found in the given
bucket, false if otherwise.
* Adds an overloaded Remove that doesn't require a key
* Updates various comments throughout the code. Notes where exceptions
are thrown.

Adds minor refactors and additions to BucketQueue

---

Assets/BaseScene.unity
Assets/Scenes.meta
Assets/Scripts/Combat/CombatData.cs
Assets/Scripts/Entity/Enemy.cs
Assets/Scripts/Entity/Player.cs

- Player max health is now 200.
- Player max mana is now 200.
- Player max Armor is now 80
- Player max evasion is still 70.
- Player starts with 100 health and 100 mana, but no armor or evasion.

Balances combat by lowering health ranges

---

Assets/Scenes.meta
Assets/Scripts/Item/Consumables/Food.cs

Completes #115 by telling fish they should be eaten.
Actually does the business by pulling the player and then the player's CombatData. Then changing stuff in CombatData.

Eating fish adds health to the player.

---

Assets/BaseScene.unity
Assets/Prefabs/PlayerSeal.prefab
Assets/Scripts/Entity/Player.cs

Adds a health bar over the player.

---

Assets/Scripts/Entity/Player.cs
Assets/Scripts/Item/Consumables/Food.cs
Assets/Scripts/Item/Consumables/HealthPotion.cs

- Updates the health bar on fish or health potion pick up
- Adds a heal method to player
- Checks that a player's health isn't going over the maximum health

Update the health bar everywhere.
